AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Innov8's lambda layers to be used across lambda functions

Resources:
  GeohashingLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GeohashingLayer
      Description: Geohashing dependency layer to be used across lambda functions
      LicenseInfo: "MIT"
      ContentUri: ./geohashing-layer/nodejs
      CompatibleRuntimes:
        - nodejs16.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs16.x

  RandomStringGeneratorLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: RandomStringGeneratorLayer
      Description: Random string generator layer to be used across lambda functions
      LicenseInfo: "MIT"
      ContentUri: ./random-string-generator-layer/nodejs
      CompatibleRuntimes:
        - nodejs16.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: nodejs16.x