AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Innov8's lambda layers to be used across lambda functions

Resources:
  GeohashingLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GeohashingLayer
      Description: Geohashing dependency layer to be used across lambda functions
      LicenseInfo: "MIT"
      ContentUri: ./geohashing-layer/nodejs
      CompatibleRuntimes:
        - nodejs16.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs16.x

  RandomStringLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: RandomStringLayer
      Description: Random string layer to be used across lambda functions
      LicenseInfo: "MIT"
      ContentUri: ./random-string-layer/nodejs
      CompatibleRuntimes:
        - nodejs16.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs16.x